### ISSUE TITLE
using with gokit

### ISSUE THREAD

**Issue by ghost** [mishudark/eventhus#9]
https://github.com/go-kit/kit

gokit only supports simple RPC.

I dont knwo if eventhus is dead, but it looks like it can pretty easily work with gokit.

**Comment by mishudark** [comment]
Hi, you discovered one secret about eventhus, the main idea was to use it after go kit transport layer, the project is still alive, I’m planning to improve the project this summer 

Of course help is welcome 😃

**Comment by ghost** [comment]
Yeah I kind of was thinking that was your plan from the shape of the code.

Yes I am willing to help.

I am also playing around with integrating it with a rendering layer like
buffalo.

Do you have a roadmap, so I can see where to help ?

One thing I see if that you need a caches aggregator so that new clients
can get all the aggregation / view models instead of replaying all the
events back.

Then I would use the buffalo generators to gen lots of event code.
Buffalo has the concept of actions, which is just like commands in CQRS
system.

Checkout the video
https://gobuffalo.io/en/docs/generators#built-in

**Comment by mishudark** [comment]
instead of cache, it's required to have an aggregation db, in one place all the events are stored and in another the final state is represented 

There are some tasks on the project side of this repo, related with errors management and CI

buffalo generators look really cool :)

**Comment by ghost** [comment]
Ok I get what you mean about the read dB for the views.

What does "project side" mean ? Sorry don't understand...

Yeah I am toying with using buffalo as the web layer and also generating
the event sourcing layer too.

**Comment by mishudark** [comment]
Here 

<img width="481" alt="using_with_gokit_ _issue__9_ _mishudark_eventhus" src="https://user-images.githubusercontent.com/211144/42532812-48acce86-8488-11e8-9a37-7ef2ce827d7a.png">

**Comment by ghost** [comment]
Got ya.

Will have a look tonight.

Thanks

**Comment by ghost** [comment]
I am planning to use this with Vuejs for web and flutter for mobile.

Question. The most important thing is for the event that alters an aggravates to produce as event that the client subscribes too. Like event type of " created X row " with the payload being the row data.
That way the GuI just magically updates it's views which are mapped to the aggravates 1:1.

Do you know what I mean ?

**Comment by ghost** [comment]
Oops. Reopening ...

**Comment by mishudark** [comment]
Flutter <3

Talking about UX, it is better to use optimistic models on Fe / Mobile ;)

**Comment by ghost** [comment]
what is an optimistic model is ?

**Comment by mishudark** [comment]
https://uxplanet.org/optimistic-1000-34d9eefe4c05

**Comment by ghost** [comment]
Ok i totally get what you mean about Optimistic GUI.  

There is a nice gokit NATS over GRPC example here btw:https://github.com/shijuvar/gokit/tree/master/example

The store is mongoDB. 

---

However this looks more complete:
https://github.com/shijuvar/go-distributed-sys
